#!/usr/bin/python
"""
When you copy-and-paste a hierarhical sheet from another project, the "instance name"
(shown as "Sheet: ...") isn't changed and Kicad complains about that
when generating the Netlist.

This tool increments the instance name suffixes by one
"""

import sys, re
filename = sys.argv[1]

write_to_file = False
if len(sys.argv) > 2 and sys.argv[2] == "--write":
    print "*** Writing to file..."
    write_to_file = True

if write_to_file:
    ans = raw_input("Did you close the Schematic Editor? [y/n] ")
    if ans != "y":
        print "Schematic Editor should be closed before running this."
        exit()


with open(filename, 'r+b') as f:
    lines = []
    widlist = []
    curr_id = 0
    pattern = re.compile('(^F0 ")([a-zA-Z-_0-9]+)(".*)')
    for line in f:
        ref = pattern.search(line)
        if ref:
            wid = ref.group(2)
            if wid in widlist:
                new_name = "{0}-{1}".format(wid, curr_id)
                print "duplicate instance:", wid, "renamed to: ", new_name
                new_line = pattern.sub("\\1%s\\3" % new_name, line)
                lines.append(new_line)
                curr_id += 1
            else:
                print "found instance: ", wid, " (first occurrence)"
                lines.append(line)

            widlist.append(wid)
        else:
            lines.append(line)

    new_content = ''.join(lines)

    if write_to_file:
        f.seek(0)
        f.write(new_content)
        f.truncate()
    else:
        print "**** This was a dry run, use with '--write' parameter to write to the file."
